### ISSUE TITLE
Extract connection details to properties file

### ISSUE THREAD

**Issue by mccorby** [OpenMined/AndroidWorker#30]
Currently the IP to connect the worker is hard-coded in `MainActivity`.
This value can be extracted to the local properties file.

**Comment by karlhigley** [comment]
Seems like the tricky part would be handling the additional hard coded IP in the network security config.

**Comment by mccorby** [comment]
Uhmmm.... good point.
Would this work in `network_security_config`?

```<base-config cleartextTrafficPermitted="true"/>```

**Comment by mccorby** [comment]
It works with the emulator.
